[package]
name = "meg_file_creator"
version = "0.1.0"
authors = ["Ulrich Johan Isachsen <ulrich@isachsen.org>"]
edition = "2018"

[dependencies]
structopt = { version = "0.3", default-features = false }
byteorder = { version = "1.3.2" }
